### ISSUE TITLE
Multiple effects and multiple items in effect block

### ISSUE THREAD

**Issue by Jaco-Daan** [de-longhi/Realms_in_Exile_Tools#2]
There is a problem when reading the history files:

When there are 2 effects inside the same date, such as:
```
3711.4.3 = {
    birth = yes        
    effect = {
        learn_language = language_sindarin
        learn_language = language_quenya
    }    
    give_nickname = nick_the_tall
    effect = {
        add_character_flag = {
            flag = had_nickname_event
        }
        add_trait_xp = {
            trait = blood_of_numenor
            value = 100
        }
    }
}
```
It only evaluates the first effect block, thereby skipping the second effect block (which in this case holds the piece of code that we wanted to extract, namely the "add_trait_xp" part)

Another issue is that the code assumes the "add_trait_xp" (or whatever you're searching for inside the effect blocks) is the first thing in the effect block, so in cases like this:
```
3713.2.12 = {
    birth = yes        
    effect = {
        learn_language = language_sindarin
        learn_language = language_quenya
        add_trait_xp = {
            trait = blood_of_numenor
            value = 100
        }
    }    
}
```
It will evaluate the "learn_language = ..." and skip over the "add_trait_xp" part

**Comment by de-longhi** [comment]
Would you please confirm whether the bug has been fixed with the recent commit.

**Comment by Jaco-Daan** [comment]
Can confirmed it's been fixed.
